# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.
This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

```{r}
1 + 1
```


## Agora sim

for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.
for additional discussion of literate programming.This is a book created from markdown and executable code.

### testando bem

for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.

#### tet 4

for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.for additional discussion of literate programming.This is a book created from markdown and executable code.vv